### ISSUE TITLE
Import material icons and fonts? (Webpack with NPM)

### ISSUE THREAD

**Issue by pablorsk** [FountainJS/generator-fountain-webapp#109]
We need insert material (1.1.0-rc.5) on own project. With `generator-gulp-angular` we don't have problems, but now with this generator, we have problems with fotns and icons.

We have this:

``` javascript
import 'angular-material';
```

And work, but fonts and icons are not loading....

We try with `angular-material-icons` and `material-icons`, but any option is OK.

**Comment by micaelmbagira** [comment]
Can you share the conf you are using please ? Just need to copy the `.yo.rc.json`, are you using webpack, systemjs, bower... ?

**Comment by pablorsk** [comment]
Yes, no problem. This is my `.yo.rs.json` file:

```
{
  "generator-fountain-angular1": {
    "version": "0.6.0",
    "props": {
      "framework": "angular1",
      "modules": "webpack",
      "js": "typescript",
      "css": "scss",
      "resolved": "/usr/lib/node_modules/generator-fountain-webapp/node_modules/generator-fountain-angular1/generators/app/index.js",
      "namespace": "fountain-angular1",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "skip-cache": false,
      "skip-install": false,
      "sample": "techs",
      "router": "uirouter"
    }
  }
}
```

Also, if you like check only modifications of a basic fountain webapp for angular-material: https://github.com/pablorsk/test-generator-fountain-webapp-angular-material/compare/feature/material

**Comment by micaelmbagira** [comment]
I have taken a quick look, why the text should be with Roboto font ?

**Comment by pablorsk** [comment]
First of all, thank you very much for your time @micaelmbagira.

Roboto is the font chossen for Material team. If you check material CSS, you can see code like this:

```
button,
select,
html,
textarea,
input {
  font-family: Roboto, "Helvetica Neue", sans-serif; }
```

[They recommend put a link object to Google fonts](https://material.angularjs.org/latest/CSS/typography) like this:

``` html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
```

But, if we can add fonts by npm on fountain, great feature :) Also, this an one more step for Fountain+Material, like `generator-gulp-angular`

**Comment by pablorsk** [comment]
### Proposed solution for Material Font Roboto

What you think about this solution for loading Material font with Webpack+NPM?

``` bash
$ npm install --save-dev file-loader
$ npm install --save roboto-fontface
```

conf/webpack.conf.json:

```
    loaders: [
      {
          test: /\.(eot|woff|woff2|svg|ttf)([\?]?.*)$/, loader: "file-loader"
      }
      ...
    ]
```

src/index.ts

``` javascript
import 'angular-material';
import 'angular-material/angular-material.css';
import 'roboto-fontface/css/roboto/sass/roboto-fontface-regular.scss';
```

This solution is working, but your opinion and help for future fountain+material is very important to us.

**Comment by micaelmbagira** [comment]
Yes, the problem is that you need to import Roboto font, here it says that it's not imported automatically https://material.angularjs.org/latest/CSS/typography (they import it from a CDN but  you can download it and `import '...roboto.css'`.
Then, yes if you import the font with Webpack you need `file-loader` 👍

**Comment by pablorsk** [comment]
### Proposed solution for Material Icons (Webpack with NPM)

Add [this lines](https://fonts.googleapis.com/icon?family=Material+Icons) to `index.scss`

``` css
/* fallback */
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: local('Material Icons'), local('MaterialIcons-Regular'), url(https://fonts.gstatic.com/s/materialicons/v17/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2) format('woff2');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}
```

And next, just simple add icons like this:

``` html
<md-icon>face</md-icon>
```

This solution is working. Thanks for your help @micaelmbagira.

If you like a online demo  of this, working with generator-fountain-webapp, [follow this link](https://github.com/pablorsk/test-generator-fountain-webapp-angular-material).
